### ISSUE TITLE
FileNotFoundError: Could not find: nvinfer.dll. Is it on your PATH?

### ISSUE THREAD

**Issue by My12123** [Kiteretsu77/FAST_Anime_VSR#3]
Graphics processor 1
NVIDIA GeForce RTX 2060 SUPER
Driver version: 31.0.15.3667
Date of development: 12.07.2023
DirectX Version: 12 (FL 12.1)
Dedicated GPU memory 1.4/8.0 GB
Total GPU memory 0.2/19.9 GB
Graphics processor RAM 1.5/27.9 GB
TensorRT-8.6.1.6
```
(venv) F:\FAST_Anime_VSR>python main.py
Traceback (most recent call last):
  File "F:\FAST_Anime_VSR\main.py", line 1, in <module>
    import tensorrt
  File "F:\FAST_Anime_VSR\venv\lib\site-packages\tensorrt\__init__.py", line 127, in <module>
    ctypes.CDLL(find_lib(lib))
  File "F:\FAST_Anime_VSR\venv\lib\site-packages\tensorrt\__init__.py", line 81, in find_lib
    raise FileNotFoundError(
FileNotFoundError: Could not find: nvinfer.dll. Is it on your PATH?
Note: Paths searched were:
['F:\\FAST_Anime_VSR\\venv\\Scripts', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\libnvvp', 'C:\\VulkanSDK\\1.3.250.1\\Bin', 'C:\\Program Files (x86)\\CodeSynthesis XSD 4.0\\bin\\', 'C:\\Program Files (x86)\\CodeSynthesis XSD 4.0\\bin64\\', 'C:\\Program Files\\ImageMagick-7.1.1-Q16-HDRI', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\libnvvp', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.3\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.3\\libnvvp', 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64_win\\compiler', 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath', 'C:\\ProgramData\\Oracle\\Java\\javapath', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\libnvvp', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.1\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.1\\libnvvp', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\WINDOWS\\System32\\OpenSSH\\', 'C:\\Program Files (x86)\\Boxcryptor\\bin\\', 'C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\', 'C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\', 'C:\\Program Files\\WireGuard\\', 'C:\\Program Files (x86)\\HP\\Common\\HPDestPlgIn\\', 'F:\\Git\\cmd', 'C:\\Program Files (x86)\\Sudowin\\Clients\\Console', 'C:\\Program Files\\nodejs\\', 'C:\\Program Files\\Docker\\Docker\\resources\\bin', 'F:\\New Folder\\', 'C:\\Program Files\\Cloudflare\\Cloudflare WARP\\', 'C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2022.1.0\\', 'C:\\Users\\tchot\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\', 'C:\\Users\\tchot\\AppData\\Local\\Programs\\Python\\Python310\\', 'C:\\Users\\tchot\\scoop\\shims', 'C:\\Users\\tchot\\AppData\\Local\\Programs\\Python\\Python38\\Scripts\\', 'C:\\Users\\tchot\\AppData\\Local\\Programs\\Python\\Python38\\', 'F:\\1\\envs\\mi1\\bin\\\\..\\extras\\CUPTI\\lib64', 'C:\\WINDOWS', 'C:\\WINDOWS', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\libnvvp', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.3\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.3\\libnvvp', 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64_win\\compiler', 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath', 'C:\\ProgramData\\Oracle\\Java\\javapath', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\libnvvp', 'C:\\Program Files\\Microsoft\\jdk-11.0.12.7-hotspot\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.1\\bin', 'C:\\Program Files\\NVIDIA GP', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin\\nvinfer.dll', ''
``` 
How to fix it?

**Comment by Kiteretsu77** [comment]
As my instruction in step3 of the Windows installation, did you stricly follow https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-zip? Usually, as long as users follow this instruction, the TensorRT will be installed and you can directly use "pip install tensorrt" in python interface. 
Thanks!

**Comment by My12123** [comment]
Can I have more detailed instructions?

**Comment by My12123** [comment]
I fixed this by adding the necessary files to venv\Scripts
